### ISSUE TITLE
Nested sortables with Livewire event handling

### ISSUE THREAD

**Issue by juliomotol** [asantibanez/laravel-blade-sortable#2]
Is there any way I could handle the `wire:onSortOrderChange` and know whether it has been move from one list to another?

**Comment by SquareBeard** [comment]
I think my problem is related.
I need at least the group in the handleSortOrderChange method, or another customizable parameter.

**Comment by JordivdB** [comment]
Same problem here, right now theres no way to know in what dropzone you dragged your items. @asantibanez

**Comment by asantibanez** [comment]
Hi all! Thanks for your interest in the package.

This issue has been addressed in v1.1.0. 

`wire:onSortOrderChange` gets called on any interaction with the drop zone: sorting, adding, removing.

Check it out.

**Comment by juliomotol** [comment]
Sorry, I don't understand. How was this resolved?

v1.1.0 is tagged at the same commit as v1.0.3 (commit `0bdd90f`)
![image](https://user-images.githubusercontent.com/21353103/112415657-25c4dc00-8d5f-11eb-879e-0bdc473c08ce.png)

**Comment by asantibanez** [comment]
Thanks for the update @juliomotol .

Wrong version was tagged.

Just fixed. 👍

**Comment by SquareBeard** [comment]
I still don't understand how that update fix this ?
Maybe I'm missing something.

**Comment by asantibanez** [comment]
Don't follow @SquareBeard . Inside your Livewire component you have 2 drop zones and want to get updated on both with `wire:onSortOrderChange`?

**Comment by SquareBeard** [comment]
Sorry maybe I should have done another issue, it does not seem related anymore.
I want to know which drop zone is calling onSortOrderChange.
My drop zones are created dynamically, I can't use a different method for each zone. I just need the group name or some other parameter to identify the group.
Something like 
```php
function handleSortOrderChange($groupName) { ... }
```

Does that make more sense ?

**Comment by juliomotol** [comment]
I'm sorry @asantibanez, I'm with @SquareBeard on this one.

The concern was:

> Is there any way I could handle the wire:onSortOrderChange and know whether it has been move from one list to another?

And yet, the new release feels like a refactor rather than a fix.

Taking an inspiration from [SortableJs' event parameters](https://github.com/SortableJS/Sortable#event-object-demo), we could do:

```
function handleSortOrderChange($order, $toGroup, $fromGroup) { ... }
```

**Comment by asantibanez** [comment]
This is doable. How would you identify the containers? With an id in the sortable component?

**Comment by SquareBeard** [comment]
Sounds good, but 'from' before 'to' feels more natural to me.
```php
function handleSortOrderChange($order, $from, $to) { ... }
```

**Comment by asantibanez** [comment]
Hey @SquareBeard @juliomotol 

Have this one working. I am sending this info the Livewire component:

![image](https://user-images.githubusercontent.com/5126648/112702096-648e8b00-8e60-11eb-95f9-86de637e1c8f.png)

Example callback

![image](https://user-images.githubusercontent.com/5126648/112702141-86880d80-8e60-11eb-9777-a12758066675.png)

Demo

![2021-03-26 18 24 57](https://user-images.githubusercontent.com/5126648/112702205-ae777100-8e60-11eb-92e8-b8267721ea96.gif)


How's that looking?

**Comment by juliomotol** [comment]
@asantibanez Looking like a charm. I really loved that you included the old sort order. Might come handy in the future.

**Comment by asantibanez** [comment]
Resolved in v1.2.0 👍

https://github.com/asantibanez/laravel-blade-sortable/releases/tag/v1.2.0

**Comment by SquareBeard** [comment]
Looks great, thank you.

**Comment by Hesesses** [comment]
Hello and thank you for creating this!

About the demo above. When you move "Andres" to the middle section. How I should get the data that "Andres" was moved to somewhere?

I was hoping the "name" param would show this..

I think the only way to get this data now is to compare sortOrder and previousSortOrder and remove duplicates
